# flake8: noqa

"""
    API zum Digitalisierungsfortschritt der öffentlichen Verwaltung

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from deutschland.digitale_verwaltung.api_client import ApiClient

# import Configuration
from deutschland.digitale_verwaltung.configuration import Configuration

# import exceptions
from deutschland.digitale_verwaltung.exceptions import (
    ApiAttributeError,
    ApiException,
    ApiKeyError,
    ApiTypeError,
    ApiValueError,
    OpenApiException,
)
