"""
    API zum Digitalisierungsfortschritt der öffentlichen Verwaltung

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""

import unittest

from deutschland.digitale_verwaltung.api.data_api import DataApi  # noqa: E501

from deutschland import digitale_verwaltung


class TestDataApi(unittest.TestCase):
    """DataApi unit test stubs"""

    def setUp(self):
        self.api = DataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_find_all(self):
        """Test case for find_all

        Informationen zu OZG-Leistungen und deren zugehörigen Onlinediensten  # noqa: E501
        """
        pass

    def test_find_by_filter(self):
        """Test case for find_by_filter

        Informationen zu OZG-Leistungen und deren zugehörigen Onlinediensten eingeschränkt auf Gebietskörperschaften  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
