"""
    API zum Digitalisierungsfortschritt der öffentlichen Verwaltung

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""

import unittest

from deutschland.digitale_verwaltung.api.ars_api import ARSApi  # noqa: E501

from deutschland import digitale_verwaltung


class TestARSApi(unittest.TestCase):
    """ARSApi unit test stubs"""

    def setUp(self):
        self.api = ARSApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_find_all1(self):
        """Test case for find_all1

        Informationen zu Gebietskörperschaften in Deutschland  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
