"""
    API zum Digitalisierungsfortschritt der öffentlichen Verwaltung

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.digitale_verwaltung.model.dv_data_dto import DvDataDto
from deutschland.digitale_verwaltung.model.pageable_object import PageableObject
from deutschland.digitale_verwaltung.model.sort_object import SortObject

from deutschland import digitale_verwaltung

globals()["DvDataDto"] = DvDataDto
globals()["PageableObject"] = PageableObject
globals()["SortObject"] = SortObject
from deutschland.digitale_verwaltung.model.page_dv_data_dto import PageDvDataDto


class TestPageDvDataDto(unittest.TestCase):
    """PageDvDataDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPageDvDataDto(self):
        """Test PageDvDataDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PageDvDataDto()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
