"""
    API zum Digitalisierungsfortschritt der öffentlichen Verwaltung

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.digitale_verwaltung.model.dv_data_dto import DvDataDto

from deutschland import digitale_verwaltung


class TestDvDataDto(unittest.TestCase):
    """DvDataDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDvDataDto(self):
        """Test DvDataDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DvDataDto()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
